#!/bin/bash

MONTHS()
{
    read month
    case $month in
        1|01) _FULL=January;;
        2|02) _FULL=Feburay;;
        3|03) _FULL=March;;
        4|04) _FULL=April;;
        5|05) _FULL=May;;
        6|06) _FULL=July;;
        7|07) _FULL=June;;
        8|08) _FULL=August;;
        9|09) _FULL=September;;
        10) _FULL=October;;
        11) _FULL=November;;
        12) _FULL=December;;
        *) echo "Unknown month"
            echo "error"
        ;;
    esac
}

